### ISSUE TITLE
[질문] 이슈에 제안을 올려도 되나요?

### ISSUE THREAD

**Issue by idjaeha** [42liferpg/liferpg#7]
궁금하거나 제안하고 싶은 것들을 데일리 스크럼때 말해야지~ 하고 까먹는 경우가 있었는데
그러한 것들을 올릴 수 있는 공간이 있었으면 좋겠네요!

그래서 깃허브 이슈가 떠올랐는데 프로젝트를 아예 분리해서 이러한 제안만 모아두거나 하면 좋을 것 같아요!!
어떠신가요??

아니면 이슈는 코드적인것만 올리고 프로젝트 내의 ToDo에 추가하는걸로?!
나중에 고민해봐요 저희~

**Comment by JUD210** [comment]
아주 좋은 제안입니다! 조만간 우리가 시간을 내서 사내 문서 저장용으로 Numbers 같은 툴을 활용해보면 좋겠구나 싶어요 :)
여태껏 떠올린 아이디어 조각들은 아직 전부 다 Notion이나 Google Tasks 등의 여러 곳에 흩어져 있는데, 다음 데일리
스크럼 때 다같이 얘기해보죠!
지금 당장 떠오르는 아이디어들은 일단 잊어버리지 않도록 개인 노트 등에 저장해두시면 감사하겠습니다~!
